const fs = require('fs');
let code = fs.readFileSync('src/services/localAiService.ts', 'utf8');

code = code.replace(
    /if \(parsed && \(parsed\.chatResponse \|\| parsed\.intent\)\) \{\n\s*console\.log\(`\[LLM Pipeline\] Tier 3 Groq \(\$\{groqModel\}\) Success`\);\n\s*return parsed;\n\s*\}/g,
    `if (parsed && (parsed.chatResponse || parsed.intent)) {
                        console.log(\`[LLM Pipeline] Tier 3 Groq (\${groqModel}) Success\`);
                        if (parsed.chatResponse) {
                            parsed.chatResponse += "\\n\\n> ⚠️ **Notice:** Real-time Google Search Grounding is temporarily disabled because your Gemini API quota was exceeded. This response was generated by a fallback model and may not contain live data.";
                        }
                        return parsed;
                    }`
);

fs.writeFileSync('src/services/localAiService.ts', code);
